[versions]
paper = "1.21.5-R0.1-SNAPSHOT"
minecraft = "1.21.5"
yarnMappings = "1.21.5+build.1"
fabricLoader = "0.16.14"
fabricApi = "0.114.1+1.21.5"
fabricLoom = "1.10.1"
spigot = "1.21.5-R0.1-SNAPSHOT"
velocity = "3.4.0-SNAPSHOT"
bungeecord = "1.20-R0.3-SNAPSHOT"
gson = "2.10.1"
shadow = "8.3.3"
lombok = "1.18.26"

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
mojang-minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarnMappings" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricLoader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabricApi" }
spigot = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
bungeecord = { group = "net.md-5", name = "bungeecord-api", version.ref = "bungeecord" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabricLoom" }
maven-publish = { id = "maven-publish" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
