[versions]
jvm = "2.0.21"
paper = "1.21.5-R0.1-SNAPSHOT"
minecraft = "1.21.5"
yarnMappings = "1.21.5+build.1"
fabricLoader = "0.16.14"
fabricApi = "0.114.1+1.21.5"
fabricKotlin = "1.13.3+kotlin.2.1.21"
fabricLoom = "1.10.1"
kotlinPlugin = "2.1.21"
spigot = "1.21.5-R0.1-SNAPSHOT"
velocity = "3.4.0-SNAPSHOT"
bungeecord = "1.20-R0.3-SNAPSHOT"
gson = "2.10.1"
shadow = "8.3.3"

[libraries]
stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "jvm" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
mojang-minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarnMappings" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricLoader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabricApi" }
fabric-language-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabricKotlin" }
spigot = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
bungeecord = { group = "net.md-5", name = "bungeecord-api", version.ref = "bungeecord" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinPlugin" }
fabric-loom = { id = "fabric-loom", version.ref = "fabricLoom" }
maven-publish = { id = "maven-publish" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
